### ISSUE TITLE
Decide to delete MVC Application in Solution.

### ISSUE THREAD

**Issue by mfarkan** [mfarkan/My-Own-Style#12]
@alicoskun What do you think of deleting the MVC application in Solution. As you know, I had started to write Angular application and I wrote some modules even. We can learn Angular and its Infrastructure. It could teach us so many technics of SPA's and TypeScript. 

Please write your own Answer.

**Comment by alicoskun** [comment]
I think it would be better. If you have already started to develop an SPA app, we don't need MVC.

**Comment by mfarkan** [comment]
Well, I have started developing a SPA with Angular. Even I developed a localize module (i18n), OIDC module and login-logout flow. I had chosen an open-source bootstrap template but it still in private mode. What do you think of Angular? Is it matter to continue with Angular or any other SPA's? @alicoskun
